"""add pricing columns and credit transactions

Revision ID: 2708d2770e53
Revises: 597f84499f8d
Create Date: 2026-02-19 17:20:04.711119
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2708d2770e53'
down_revision: Union[str, None] = '597f84499f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.Column('balance_after_pence', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('grant', 'booking_payment', 'cancellation_credit', 'admin_adjustment', 'payment_reversal', name='transaction_type'), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_txn_user_org', 'credit_transactions', ['user_id', 'organisation_id'], unique=False)
    op.add_column('membership_tiers', sa.Column('early_booking_fee_pence', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('membership_tiers', sa.Column('floodlight_booking_fee_pence', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('org_memberships', sa.Column('credit_balance_pence', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_memberships', 'credit_balance_pence')
    op.drop_column('membership_tiers', 'floodlight_booking_fee_pence')
    op.drop_column('membership_tiers', 'early_booking_fee_pence')
    op.drop_index('ix_credit_txn_user_org', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    # ### end Alembic commands ###
