"""initial schema

Revision ID: 448999d3e244
Revises: 
Create Date: 2026-02-17 08:15:05.889783
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '448999d3e244'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
