"""add user preferences

Revision ID: 597f84499f8d
Revises: 258480e72486
Create Date: 2026-02-19 16:09:44.813699
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '597f84499f8d'
down_revision: Union[str, None] = '258480e72486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('preferred_start_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prefs_user_org', 'user_preferences', ['user_id', 'organisation_id'], unique=False)
    op.create_index('ix_prefs_user_org_priority', 'user_preferences', ['user_id', 'organisation_id', 'priority'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prefs_user_org_priority', table_name='user_preferences')
    op.drop_index('ix_prefs_user_org', table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
