"""add coach tiers, max_daily_minutes, booking_window_time

Revision ID: f322bc729171
Revises: 448999d3e244
Create Date: 2026-02-17 10:45:16.504287
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f322bc729171'
down_revision: Union[str, None] = '448999d3e244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
